#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fooxboy.MusicX.AndroidApp.Resource", IsApplication=true)]

namespace Fooxboy.MusicX.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F060004
			public const int colorAccent = 2131099652;
			
			// aapt resource value: 0x7F060002
			public const int colorPrimary = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int colorPrimaryDark = 2131099651;
			
			// aapt resource value: 0x7F060005
			public const int colorTitleBar = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int ic_launcher_background = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F070002
			public const int activity_horizontal_margin = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int activity_vertical_margin = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010002
			public const int androicon = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int androicon_round = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int androicon_smol = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int androidicon_pro = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int arrow = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int button = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int exit = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int favorites = 2130771977;
			
			// aapt resource value: 0x7F010010
			public const int ic_dashboard_black_24dp = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int ic_home_24dp = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int ic_home_black_24dp = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int ic_notifications_black_24dp = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int ic_search = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int ic_search_24dp = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int ic_settings_24dp = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int ic_star_24dp = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int latest = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int now = 2130771993;
			
			// aapt resource value: 0x7F010020
			public const int placeholder = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int playlist_placeholder = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int round_img = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int shadow = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int shadow_ninepatch = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int splash = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int textbox = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int user = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int vk_logo = 2130772008;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020025
			public const int authcode = 2130837541;
			
			// aapt resource value: 0x7F020017
			public const int buttonIncorrectLoginOk = 2130837527;
			
			// aapt resource value: 0x7F020008
			public const int container = 2130837512;
			
			// aapt resource value: 0x7F020010
			public const int content_frame = 2130837520;
			
			// aapt resource value: 0x7F020024
			public const int dialogTitle = 2130837540;
			
			// aapt resource value: 0x7F020023
			public const int DurationTrack = 2130837539;
			
			// aapt resource value: 0x7F020012
			public const int exit_btn = 2130837522;
			
			// aapt resource value: 0x7F020019
			public const int ImagePlaylist = 2130837529;
			
			// aapt resource value: 0x7F020002
			public const int imageView1 = 2130837506;
			
			// aapt resource value: 0x7F020020
			public const int imageViewCover = 2130837536;
			
			// aapt resource value: 0x7F020006
			public const int log_in_btn = 2130837510;
			
			// aapt resource value: 0x7F020031
			public const int menu_search = 2130837553;
			
			// aapt resource value: 0x7F020011
			public const int navigation = 2130837521;
			
			// aapt resource value: 0x7F020027
			public const int navigation_home = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int navigation_popular = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int navigation_search = 2130837545;
			
			// aapt resource value: 0x7F020030
			public const int navigation_settings = 2130837552;
			
			// aapt resource value: 0x7F020013
			public const int playlists = 2130837523;
			
			// aapt resource value: 0x7F020015
			public const int progressBarLoagingTracks = 2130837525;
			
			// aapt resource value: 0x7F020007
			public const int progressBarLogin = 2130837511;
			
			// aapt resource value: 0x7F020003
			public const int textView1 = 2130837507;
			
			// aapt resource value: 0x7F020014
			public const int textView2 = 2130837524;
			
			// aapt resource value: 0x7F020022
			public const int textViewArtist = 2130837538;
			
			// aapt resource value: 0x7F020018
			public const int textViewPlaylist = 2130837528;
			
			// aapt resource value: 0x7F020021
			public const int textViewTitle = 2130837537;
			
			// aapt resource value: 0x7F020009
			public const int toolbar = 2130837513;
			
			// aapt resource value: 0x7F020016
			public const int TracksView = 2130837526;
			
			// aapt resource value: 0x7F020026
			public const int twofactor_confirm = 2130837542;
			
			// aapt resource value: 0x7F020004
			public const int vklogin = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int vkpassword = 2130837509;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030002
			public const int activity_auth = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int activity_main = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int activity_settings = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int homeActivity = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int IncorrectLoginDialogLayout = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int PlaylistLayout = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int TrackLayout = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int twofactor_dialog = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040002
			public const int navigation = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int top_menus = 2130968579;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher = 2131034114;
			
			// aapt resource value: 0x7F050004
			public const int ic_launcher_foreground = 2131034116;
			
			// aapt resource value: 0x7F050003
			public const int ic_launcher_round = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7F080008
			public const int auth_btn = 2131230728;
			
			// aapt resource value: 0x7F080007
			public const int auth_caption = 2131230727;
			
			// aapt resource value: 0x7F080009
			public const int login_hint = 2131230729;
			
			// aapt resource value: 0x7F080012
			public const int MusicTitleString = 2131230738;
			
			// aapt resource value: 0x7F080011
			public const int PlaylistsTitleString = 2131230737;
			
			// aapt resource value: 0x7F080010
			public const int pwd_hint = 2131230736;
			
			// aapt resource value: 0x7F080013
			public const int settings_main = 2131230739;
			
			// aapt resource value: 0x7F080003
			public const int title_home = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int title_pop = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int title_search = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int title_settings = 2131230726;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090002
			public const int CustomTheme = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Splash = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
