#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fooxboy.MusicX.AndroidApp.Resource", IsApplication=true)]

namespace Fooxboy.MusicX.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryBack = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorTitleBar = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_launcher_background = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int androicon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int androicon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int androicon_smol = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int androidicon_pro = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int arrow = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int arrow_down = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int audio_menu = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int back_ic = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int button = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int exit = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int favorites = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int home_menu = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int ic_dashboard_black_24dp = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int ic_home_24dp = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int ic_home_black_24dp = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int ic_notifications_black_24dp = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int ic_search = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int ic_search_24dp = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int ic_settings_24dp = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int ic_star_24dp = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int latest = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int next_ic = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int now = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int outline_pause_black_24dp = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int placeholder = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int play = 2130903065;
			
			// aapt resource value: 0x7F03001B
			public const int playlist_placeholder = 2130903067;
			
			// aapt resource value: 0x7F03001A
			public const int play_ic = 2130903066;
			
			// aapt resource value: 0x7F03001C
			public const int round_img = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int search_menu = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int settings_menu = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int shadow = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int skip = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int skip_back = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int splash = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int star_menu = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int textbox = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int user = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int vk_logo = 2130903078;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040005
			public const int artistPlaylistView = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int artistTrackMainPlayer = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int artist_blocks = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int artist_image = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int artist_name = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int authcode = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int backButtonTrackMainPlayer = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int buttonIncorrectLoginOk = 2130968588;
			
			// aapt resource value: 0x7F040000
			public const int CardButton = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CardCaption = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CardList = 2130968578;
			
			// aapt resource value: 0x7F04000D
			public const int closeButtonMainPlayer = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int container = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int content_frame = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int countTracksPlaylistView = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int coverPlaylistView = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int coverTrackMainPlayer = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int dialogTitle = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int dumbcat_button = 2130968596;
			
			// aapt resource value: 0x7F040003
			public const int DurationTrack = 2130968579;
			
			// aapt resource value: 0x7F040015
			public const int durationTrackMainPlayer = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int exit_btn = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int fooxboy_button = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int genrePlaylistView = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int giveupButton = 2130968601;
			
			// aapt resource value: 0x7F040004
			public const int ImagePlaylist = 2130968580;
			
			// aapt resource value: 0x7F04001A
			public const int imageView1 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int imageViewCover = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int list_playlists = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int list_plists = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int list_recommendations = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int list_tracks = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int log_in_btn = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int menu_search = 2130968609;
			
			// aapt resource value: 0x7F040024
			public const int miniplayerLayout = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int miniplayer_frame = 2130968613;
			
			// aapt resource value: 0x7F040022
			public const int miniPlayer_NextBtn = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int miniPlayer_Playbtn = 2130968611;
			
			// aapt resource value: 0x7F040026
			public const int namePlaylistView = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int navigation = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int navigation_home = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int navigation_popular = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int navigation_search = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int navigation_settings = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int navigation_tracks = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int nextButtonTrackMainPlayer = 2130968621;
			
			// aapt resource value: 0x7F04002F
			public const int player_min_artist = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int player_min_cover = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int player_min_trackName = 2130968625;
			
			// aapt resource value: 0x7F04002E
			public const int playPauseButtonTrackMainPlayer = 2130968622;
			
			// aapt resource value: 0x7F040032
			public const int positionTrackMainPlayer = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int progressBarLogin = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int progressBar_library_plists = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int progressBar_recommendations = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int progressBar_tracks = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int searchEditText = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int searchPlaceholder = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int searchProgress = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int searchResults = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int seekbarTrackMainPlayer = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int settings_version = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int streamtovk_checkbox = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int textView1 = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int textView2 = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int textViewArtist = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int textViewPlaylist = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int textViewTitle = 2130968642;
			
			// aapt resource value: 0x7F040044
			public const int titlebar_title = 2130968644;
			
			// aapt resource value: 0x7F040043
			public const int titleTrackMainPlayer = 2130968643;
			
			// aapt resource value: 0x7F040045
			public const int toolbar = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int tracksPlaylistView = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int twofactor_confirm = 2130968647;
			
			// aapt resource value: 0x7F040049
			public const int vklogin = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int vkname = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int vkpassword = 2130968651;
			
			// aapt resource value: 0x7F040048
			public const int vk_pfp = 2130968648;
			
			// aapt resource value: 0x7F04004C
			public const int yearPlaylistView = 2130968652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050004
			public const int activity_artist = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int activity_auth = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int activity_main = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int activity_mainPlayer = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int activity_playlist = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int activity_playlists = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int activity_recommendations = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int activity_settings = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int activity_tracks = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int errorActivity = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int homeActivity = 2131034126;
			
			// aapt resource value: 0x7F050000
			public const int IncorrectLoginDialogLayout = 2131034112;
			
			// aapt resource value: 0x7F05000F
			public const int offlineActivity = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int player_min = 2131034128;
			
			// aapt resource value: 0x7F050001
			public const int PlaylistLayout = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int RecommendationLayout = 2131034114;
			
			// aapt resource value: 0x7F050011
			public const int searchActivity = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int todoActivity = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int toolbar = 2131034131;
			
			// aapt resource value: 0x7F050003
			public const int TrackLayout = 2131034115;
			
			// aapt resource value: 0x7F050014
			public const int twofactor_dialog = 2131034132;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int navigation = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int top_menus = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int auth_btn = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int auth_caption = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int login_hint = 2131230725;
			
			// aapt resource value: 0x7F080000
			public const int MusicTitleString = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int PlaylistsTitleString = 2131230721;
			
			// aapt resource value: 0x7F080006
			public const int pwd_hint = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int settings_main = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int title_home = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int title_pop = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int title_search = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int title_settings = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int title_tracks = 2131230732;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int CustomTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int Splash = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
